import os
import re
import subprocess
import tempfile
from dotenv import load_dotenv

load_dotenv()
GCC_PATH = os.getenv('GCC_PATH', 'gcc')
GPP_PATH = os.getenv('GPP_PATH', 'g++')

# MSYS2 needs its own bin dirs on PATH to locate cc1.exe, as.exe, etc.
_MSYS2_PATHS = r'C:\msys64\mingw64\bin;C:\msys64\usr\bin'
_GCC_ENV = os.environ.copy()
_GCC_ENV['PATH'] = _MSYS2_PATHS + ';' + _GCC_ENV.get('PATH', '')

MAX_STUB_ITERATIONS = 6

# Baseline typedefs/macros applied to every patch before compilation.
# Only primitives and macros go here — unknown project types are generated by
# the stub injector so they can be pointers to __field_holder (see below).
_HEADER_PREFIX = """\
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
typedef uint8_t  u8;  typedef uint8_t  __u8;
typedef uint16_t u16; typedef uint16_t __u16; typedef uint16_t __le16; typedef uint16_t __be16;
typedef uint32_t u32; typedef uint32_t __u32; typedef uint32_t __le32; typedef uint32_t __be32;
typedef uint64_t u64; typedef uint64_t __u64; typedef uint64_t __le64; typedef uint64_t __be64;
typedef int8_t   s8;  typedef int16_t s16; typedef int32_t s32; typedef int64_t s64;
typedef unsigned int  gfp_t;
typedef unsigned long ulong;
typedef unsigned char uchar;
typedef unsigned char u_char;
typedef unsigned char byte;
typedef unsigned long usec_t;
typedef int           BOOL;
typedef int           status_t;
typedef uint32_t      quint32;
typedef uint64_t      quint64;
typedef int32_t       ogg_int32_t;
typedef int64_t       ogg_int64_t;
#define BGD_DECLARE(x) x

"""

_CPP_MARKERS = ['::', 'template<', 'template <', 'nullptr', 'override',
                'public:', 'private:', 'protected:', 'virtual ']

_RESERVED = {
    'int','char','void','short','long','float','double','signed','unsigned',
    'const','volatile','static','extern','auto','register','inline',
    'struct','union','enum','typedef','sizeof','return','if','else','for',
    'while','do','switch','case','default','break','continue','goto','this',
    'true','false','NULL','nullptr','size_t','ssize_t','ptrdiff_t',
    'uint8_t','uint16_t','uint32_t','uint64_t','int8_t','int16_t','int32_t','int64_t',
    'FILE','u8','u16','u32','u64','s8','s16','s32','s64',
}

# GCC/G++ diagnostics we turn into stubs
_PAT_TYPE      = re.compile(r"unknown type name '([A-Za-z_]\w*)'")
_PAT_TYPE_CPP  = re.compile(r"'([A-Za-z_]\w*)' does not name a type")
_PAT_FUNC      = re.compile(r"implicit declaration of function '([A-Za-z_]\w*)'")
_PAT_UNDECL    = re.compile(r"'([A-Za-z_]\w*)' undeclared")
_PAT_STRUCT    = re.compile(r"incomplete type 'struct ([A-Za-z_]\w*)'")
_PAT_STRUCT2   = re.compile(r"dereferencing pointer to incomplete type 'struct ([A-Za-z_]\w*)'")
_PAT_FIELD     = re.compile(r"(?:request for member|has no member named) '([A-Za-z_]\w*)'")
_PAT_NOT_DECL_SCOPE = re.compile(r"'([A-Za-z_]\w*)' was not declared in this scope")


def clean_patch(code: str) -> str:
    code = re.sub(r'^```(?:c|cpp|c\+\+)?\s*\n?', '', code.strip(), flags=re.MULTILINE)
    code = re.sub(r'\n?```\s*$', '', code.strip(), flags=re.MULTILINE)
    return code.strip()


def _looks_like_cpp(code: str) -> bool:
    return any(m in code for m in _CPP_MARKERS)


def _update_state(stderr: str, state: dict) -> bool:
    """Parse errors, add new identifiers to state. Return True if anything new was added."""
    before = {k: len(v) for k, v in state.items()}

    for name in _PAT_FIELD.findall(stderr):
        if name not in _RESERVED:
            state['fields'].add(name)

    for name in _PAT_STRUCT.findall(stderr) + _PAT_STRUCT2.findall(stderr):
        state['structs'].add(name)

    for name in _PAT_TYPE.findall(stderr):
        if name not in _RESERVED:
            state['types'].add(name)

    for name in _PAT_TYPE_CPP.findall(stderr):
        if name not in _RESERVED:
            state['types'].add(name)

    for name in _PAT_FUNC.findall(stderr):
        if name not in _RESERVED and name not in state['vars']:
            state['funcs'].add(name)

    for name in _PAT_UNDECL.findall(stderr):
        if name not in _RESERVED and name not in state['funcs']:
            state['vars'].add(name)

    for name in _PAT_NOT_DECL_SCOPE.findall(stderr):
        if name not in _RESERVED and name not in state['funcs'] and name not in state['types']:
            state['vars'].add(name)

    return any(len(state[k]) > before[k] for k in state)


def _build_stubs(state: dict) -> str:
    """Assemble the stub block from accumulated state."""
    lines = []

    # Reconcile names across categories so the same identifier is never declared
    # two different ways (GCC rejects that as 'redeclared as different kind').
    # Priority: type > function > variable.
    types = set(state['types'])
    funcs = set(state['funcs']) - types
    vars_ = set(state['vars']) - types - funcs

    # __field_holder: generic struct used as the target of every unknown type
    # alias. Grows with each new field access error.
    if state['fields']:
        field_decls = ' '.join(f'long long {f};' for f in sorted(state['fields']))
    else:
        field_decls = 'int _pad;'
    lines.append(f'struct __field_holder {{ {field_decls} }};')

    # Incomplete / named structs referenced directly (struct X *p)
    for name in sorted(state['structs']):
        lines.append(f'struct {name} {{ int _pad[64]; }};')

    # Unknown type aliases → pointer to the generic field holder so that
    # `var->any_field` always resolves.
    for name in sorted(types):
        lines.append(f'typedef struct __field_holder* {name};')

    # Unknown function names → int-returning, variadic so they accept ANY args.
    # (Under C23 a bare `int f();` means `(void)`, so calls with arguments would
    # spuriously fail with 'too many arguments'; `(...)` accepts any arity.)
    for name in sorted(funcs):
        lines.append(f'int {name}(...);')

    # Undeclared identifiers → plain int variables
    for name in sorted(vars_):
        lines.append(f'int {name};')

    return '\n'.join(lines) + '\n'


def _run_compiler(compiler: str, lang: str, filepath: str) -> subprocess.CompletedProcess:
    # Optional C-standard override for the -std sensitivity experiment.
    # Unset (default) => no -std flag => identical to the original harness.
    args = [compiler, '-fsyntax-only', '-w', '-x', lang, filepath]
    std = os.getenv('COMPILE_STD', '').strip()
    if std:
        args.insert(1, f'-std={std}')
    return subprocess.run(
        args, capture_output=True, text=True, timeout=15, shell=False, env=_GCC_ENV,
        encoding='utf-8', errors='replace',
    )


def _compile_with_stubs(code: str, is_cpp: bool) -> tuple[bool, str, int]:
    compiler = GPP_PATH if is_cpp else GCC_PATH
    lang     = 'c++'    if is_cpp else 'c'
    suffix   = '.cpp'   if is_cpp else '.c'

    state = {'types': set(), 'structs': set(), 'funcs': set(),
             'vars': set(), 'fields': set()}
    last_err = ''

    for _ in range(MAX_STUB_ITERATIONS):
        stubs = _build_stubs(state)
        tmp = tempfile.NamedTemporaryFile(
            suffix=suffix, mode='w', delete=False, encoding='utf-8', newline='\n'
        )
        tmp.write(stubs + _HEADER_PREFIX + code)
        tmp.close()
        try:
            result = _run_compiler(compiler, lang, tmp.name)
        finally:
            os.unlink(tmp.name)

        if result.returncode == 0:
            return True, '', sum(len(v) for v in state.values())
        last_err = result.stderr
        if not _update_state(result.stderr, state):
            break

    return False, last_err, sum(len(v) for v in state.values())


def is_compilable(code: str) -> dict:
    code = clean_patch(code)
    if len(code.strip()) < 10:
        return {'compilable': False, 'error': 'Empty or too short'}

    is_cpp = _looks_like_cpp(code)

    try:
        ok, err, n = _compile_with_stubs(code, is_cpp)
        if ok:
            return {'compilable': True, 'error': None, 'stubs_added': n}

        if not is_cpp and ('::' in code or '::' in err):
            ok2, _, n2 = _compile_with_stubs(code, is_cpp=True)
            if ok2:
                return {'compilable': True, 'error': None, 'stubs_added': n2}

        return {'compilable': False, 'error': (err or '')[:300].strip()}

    except subprocess.TimeoutExpired:
        return {'compilable': False, 'error': 'Timeout'}
    except FileNotFoundError as e:
        return {'compilable': False, 'error': f'compiler not found: {e}'}
